### ISSUE TITLE
Checkout API: After upgrade to 4.0 and installing the checkout module, the CheckoutCoreModule.forRoot() is not exposed

### ISSUE THREAD

**Issue by hazemfarahat** [SAP/spartacus#13451]
**Describe the bug**
After upgrading from Spartacus 3.3 to Spartacus 4.0 and installing the checkout feature using ng add @spartacus/checkout

**Tell us the version of Spartacus**
- 4.0

**To Reproduce**
run ng add @spartacus/checkout, the schematic will add 
`CheckoutCoreModule.forRoot()` in `spartacus-features.module.ts`
then an error is displayed during compilation:

`Error: src/app/spartacus/spartacus-features.module.ts:80:24 - error TS2339: Property 'forRoot' does not exist on type 'typeof CheckoutCoreModule'.`

**Expected behavior**
CheckoutModule exposes the forRoot function

**Comment by hazemfarahat** [comment]
according to https://github.com/SAP/spartacus/pull/13207/files there are no CheckoutCoreModule.forRoot() closing for now
