### ISSUE TITLE
[doc] Unclear migration/deprecation doc  when running into compilation

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7619]
After updating the bootcamp app to 2.0, I ran into this compilation error:

```
RROR in src/app/features/seo/custom-content-page-meta.resolver.ts:23:18 - error TS2339: Property 'resolve' does not exist on type 'ContentPageMetaResolver'.

23     return super.resolve().pipe(
                    ~~~~~~~
```
...caused by this code: https://github.com/SAP/spartacus-bootcamp/blob/master/src/app/features/seo/custom-content-page-meta.resolver.ts#L22-L30

The "Technical Changes in Spartacus 2.0" doc mentions the removal of the `resolve` function in  "ContentPageMetaResolver" in "Automated migrations of page meta resolvers" https://github.com/SAP/spartacus/blob/develop/docs/migration/2_0.md#automated-migrations-of-page-meta-resolvers

However, I could not figure out what to replace the broken code with.  I don't know if this was one of the goals of the doc. If so, this aspect could perhaps be improved.  I ended up commenting out the broken code.

**Comment by tobi-or-not-tobi** [comment]
With the new version there's no longer a need to explicitly resolve the various page meta resolver implementations. The implementation is checked on an implementation for the given provider.

See https://github.com/SAP/spartacus/blob/1a346718e84f108c909d32cb504bdf8040d4df21/projects/core/src/cms/facade/page-meta.service.ts#L59.
